apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank-container
          image: sriramyaganni/bank-webapp:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
spec:
  selector:
    app: bank
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
